sudo: required

language: ruby

services:
  - docker

env:
  matrix:
    - RESTY_REQL_PATH="lua-resty-reql/ubuntu/1.0.0"
    - RESTY_REQL_PATH="lua-resty-reql/alpine/1.0.0"

before_install:
  - docker build -t grandquista/lua-resty-reql $RESTY_REQL_PATH
  - docker run -d --network host -p 28015:28015 rethinkdb
  - docker ps -a

script:
  - docker run -h reql --network host -P grandquista/lua-resty-reql
