sudo: required

env:
  matrix:
    - RESTY_REQL_PATH="lua-resty-reql/ubuntu/1.0.0"
    - RESTY_REQL_PATH="lua-resty-reql/alpine/1.0.0"

services:
  - docker

before_install:
  - docker build -t grandquista/lua-resty-reql $RESTY_REQL_PATH
  - docker run --network host rethinkdb/rethinkdb
  - docker ps -a

script:
  - docker run grandquista/lua-resty-reql /bin/sh -c "prove -r t"
